basic.forever(function () {
    pinooBit.mesafes(DigitalPin.P0, DigitalPin.P0)
    pinooBit.buzzer(DigitalPin.P0, 0)
    pinooBit.led(DigitalPin.P0, 0)
    pinooBit.servo(DigitalPin.P0, 0)
    basic.showNumber(pinooBit.isik(AnalogPin.P0))
    basic.showNumber(pinooBit.suseviye(AnalogPin.P0))
    basic.showNumber(pinooBit.tvn(AnalogPin.P0))
    basic.showNumber(pinooBit.joysticky(AnalogPin.P0))
    basic.showNumber(pinooBit.joysticky(AnalogPin.P0))
    basic.showNumber(pinooBit.joystickx(AnalogPin.P0))
    basic.showNumber(pinooBit.pot(AnalogPin.P0))
    basic.showNumber(pinooBit.pir(DigitalPin.P0))
})
